# Java Logging confguration

# configure the console handler to log all levels
java.util.logging.ConsoleHandler.level = ALL

# set the handler for the logger
nl.tno.handlers = java.util.logging.ConsoleHandler

# set the level to log from; child loggers inherit this setting
nl.tno.level = INFO

# set the format for the SimpleFormatter
java.util.logging.SimpleFormatter.format = %1$tF %1$tT:%1$tL %1$tZ %4$s %2$s: %5$s %6$s%n
